default: &default
  adapter: postgresql
  pool: 5
  timeout: 60000
  host: localhost
  username: wiki
  password: dbpass

development:
  <<: *default
  database: wiki_dev

test:
  <<: *default
  database: wiki_test

production:
  <<: *default
